database:
  host: localhost
  port: 5432
  user: messenger_user
  password: messenger_password
  dbname: messenger_db
  sslmode: disable
  dbschema: messenger_schema

server:
  port: 8083

keycloak:
  issuer: "http://localhost:8080/realms/collab-timekit"
  client_id: "messenger-client"