name: Auto Tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # potrzebne do tagów

      - name: Calculate next tag
        id: tagger
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $LATEST_TAG"

          VERSION=$(echo "$LATEST_TAG" | sed 's/^v//' | awk -F. '{ printf("v%d.%d.%d", $1, $2, $3+1) }')
          echo "New version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create tag and push
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag ${{ steps.tagger.outputs.version }}
          git push origin ${{ steps.tagger.outputs.version }}